[package]
name = "labEC"
version = "0.1.0"
edition = "2021"

[dependencies]
num-integer = { version = "0.1.46", features = ["std", "i128"] }
rand = "0.8"
num-bigint = { version = "0.4", features = ["rand"] }
num-traits = "0.2.19"
once_cell = "1.21.3"
